"""Extended attack catalog — 27 techniques."""

ATTACKS = {
    "credential-attacks": {
        "name": "Brute Force & Credential Stuffing", "icon": "key-round",
        "mitre": "T1110", "tactic": "Credential Access", "urgency": "Critical",
        "summary": "Automated password guessing or reuse of credentials stolen from another service.",
        "history": "Password guessing is one of the oldest intrusion methods. Large breach collections and inexpensive automation evolved it into credential stuffing.",
        "workflow": ["Acquire usernames or leaked credential pairs", "Distribute attempts across IPs and devices", "Tune request rate to avoid lockouts", "Reuse a successful session for privilege escalation"],
        "signals": ["Bursts of 401/403 responses", "One source targeting many accounts", "A successful login after repeated failures", "New device or token activity after login"],
        "example": "An attacker tries a reused email/password against a shopping account. Login succeeds after 37 failures, followed by an address change.",
        "solutions": ["Use unique passwords and a password manager", "Enable phishing-resistant MFA", "Rate-limit by account and source IP", "Screen against breached-password databases", "Enforce conditional access on suspicious sessions"],
        "reference": "https://attack.mitre.org/techniques/T1110/"
    },
    "session-hijacking": {
        "name": "Session Hijacking", "icon": "cookie",
        "mitre": "T1539", "tactic": "Credential Access", "urgency": "Critical",
        "summary": "An attacker steals a valid session token to impersonate an authenticated user without knowing their password.",
        "history": "Session theft predates modern web apps and remains effective wherever tokens are transmitted or stored insecurely.",
        "workflow": ["Intercept or steal a session token (XSS, network sniff, leaked log)", "Replay the token against the target service", "Perform actions as the victim user", "Establish persistence before token expiry"],
        "signals": ["Same session token used from two different IPs", "Token reuse after logout", "Geographically impossible logins", "Sensitive actions immediately after token reuse"],
        "example": "An XSS payload on a forum page steals the visitor's session cookie and sends it to an attacker-controlled server.",
        "solutions": ["Use HttpOnly and SameSite=Strict cookies", "Bind sessions to IP or device fingerprint where feasible", "Implement short-lived tokens with silent refresh", "Invalidate all sessions on password change"],
        "reference": "https://attack.mitre.org/techniques/T1539/"
    },
    "password-spraying": {
        "name": "Password Spraying", "icon": "spray-can",
        "mitre": "T1110.003", "tactic": "Credential Access", "urgency": "High",
        "summary": "A small number of common passwords are tried against many accounts to avoid per-account lockouts.",
        "history": "Spraying emerged as organizations began locking accounts after a few failed attempts, rendering traditional brute force ineffective.",
        "workflow": ["Enumerate valid usernames (OSINT, API responses)", "Select 2-3 most common passwords for the period", "Space attempts to stay below lockout thresholds", "Collect successful logins"],
        "signals": ["Many accounts each receiving exactly 1-2 failed logins", "Low-and-slow pattern over hours", "Attempts coincide with peak hours to blend in"],
        "example": "An attacker tries 'Summer2024!' against all 500 company email addresses over two hours, succeeding on 4 accounts.",
        "solutions": ["Enforce MFA organization-wide", "Alert on distributed low-volume failures", "Use passwordless authentication where possible"],
        "reference": "https://attack.mitre.org/techniques/T1110/003/"
    },
    "sql-injection": {
        "name": "SQL Injection", "icon": "database-zap",
        "mitre": "T1190", "tactic": "Initial Access", "urgency": "Immediate",
        "summary": "Untrusted input changes the structure or meaning of an application database query.",
        "history": "SQL injection became prominent as dynamic database-backed websites spread. It remains dangerous wherever applications concatenate input into queries.",
        "workflow": ["Find a database-backed parameter", "Probe quoting and error behavior", "Infer database structure", "Extract, modify, or delete data", "Attempt OS execution where database privileges allow"],
        "signals": ["UNION SELECT or comment markers in parameters", "Database syntax errors in responses", "Unusual response sizes or latency", "Schema enumeration requests"],
        "example": "A vulnerable product lookup concatenates an ID. A boolean condition in the input causes every product to be returned.",
        "solutions": ["Use parameterized queries exclusively", "Apply least privilege to database accounts", "Enable database audit logs", "Add WAF rules for common injection patterns", "Run SAST/DAST on every input path"],
        "reference": "https://owasp.org/www-community/attacks/SQL_Injection"
    },
    "command-injection": {
        "name": "Command Injection", "icon": "terminal-square",
        "mitre": "T1059", "tactic": "Execution", "urgency": "Immediate",
        "summary": "Attacker-controlled input reaches an operating-system command interpreter.",
        "history": "Command injection has persisted from early CGI programs through modern API wrappers that invoke shell tools.",
        "workflow": ["Locate input passed to a system utility", "Test shell separators", "Execute discovery commands", "Download tooling or establish persistence", "Access secrets and move laterally"],
        "signals": ["Shell metacharacters in parameters", "Unexpected child processes spawned by the web service", "Outbound connections immediately after a request"],
        "example": "A diagnostic endpoint runs a ping command using an unsanitized hostname. A separator launches a second command.",
        "solutions": ["Remove shell execution; use native library APIs", "Use argument arrays instead of shell strings", "Run services under low-privilege accounts", "Apply sandboxing or seccomp profiles"],
        "reference": "https://attack.mitre.org/techniques/T1059/"
    },
    "cross-site-scripting": {
        "name": "Cross-Site Scripting (XSS)", "icon": "code-xml",
        "mitre": "T1189", "tactic": "Initial Access", "urgency": "High",
        "summary": "Untrusted content executes as script in another user's browser.",
        "history": "XSS emerged with scriptable web applications and now appears as reflected, stored, and DOM-based variants.",
        "workflow": ["Find reflected or stored input", "Determine injection context (HTML, attribute, URL, script)", "Craft a context-specific payload", "Deliver it to a victim", "Steal data or perform actions in victim session"],
        "signals": ["Script tags or event handlers in input", "Unexpected DOM mutation", "CSP violation reports", "Session reuse from a new device"],
        "example": "A comment field stores unencoded HTML. Anyone viewing the page executes the attacker's script in the site origin.",
        "solutions": ["Apply contextual output encoding", "Use frameworks that escape by default", "Deploy strict Content-Security-Policy", "Mark cookies HttpOnly and SameSite"],
        "reference": "https://owasp.org/www-community/attacks/xss/"
    },
    "ldap-injection": {
        "name": "LDAP Injection", "icon": "directory",
        "mitre": "T1110", "tactic": "Credential Access", "urgency": "High",
        "summary": "Untrusted input alters LDAP query logic, enabling unauthorized authentication or data extraction.",
        "history": "LDAP injection follows the same logic as SQL injection but targets directory services common in enterprise authentication.",
        "workflow": ["Identify login or search fields backed by LDAP", "Insert LDAP filter characters", "Bypass authentication or enumerate directory", "Extract user attributes or credentials"],
        "signals": ["Special LDAP characters in username fields", "Authentication success without a valid password", "Directory attribute enumeration requests"],
        "example": "A login field processes )(uid=*)( which causes the LDAP filter to match any user, bypassing authentication.",
        "solutions": ["Sanitize input by escaping LDAP special characters", "Use allow-lists for expected username formats", "Implement proper LDAP query parameterization"],
        "reference": "https://owasp.org/www-community/attacks/LDAP_injection"
    },
    "path-traversal": {
        "name": "Path Traversal", "icon": "folder-search",
        "mitre": "T1083", "tactic": "Discovery", "urgency": "High",
        "summary": "Manipulated paths escape an intended directory and access unauthorized files.",
        "history": "Traversal flaws have affected file servers, archives, download handlers, and template systems across operating systems.",
        "workflow": ["Find a filename or path parameter", "Submit encoded parent-directory sequences", "Probe known configuration files", "Read secrets or source code", "Use exposed credentials for further access"],
        "signals": ["../ or encoded equivalents in URL parameters", "Requests for password or configuration files", "Abnormal download sizes"],
        "example": "A download endpoint joins user input to an upload folder without checking the canonical path.",
        "solutions": ["Resolve canonical paths and verify they remain beneath an allow-listed root", "Map opaque identifiers to server-side files", "Run with minimal filesystem permissions"],
        "reference": "https://owasp.org/www-community/attacks/Path_Traversal"
    },
    "file-upload-abuse": {
        "name": "Malicious File Upload", "icon": "file-warning",
        "mitre": "T1190", "tactic": "Initial Access", "urgency": "Critical",
        "summary": "An attacker uploads a file that the server executes or that compromises other users.",
        "history": "Upload abuse ranges from simple web shells to polyglot files that bypass content checks.",
        "workflow": ["Find a file upload endpoint", "Bypass extension and MIME checks", "Upload a web shell or malicious document", "Execute via direct URL or trigger server processing"],
        "signals": ["Uploads of .php .asp .jsp extensions", "MIME type mismatch", "Execution of a recently uploaded file", "Outbound connection from the web server process"],
        "example": "An avatar upload endpoint only checks file extension client-side. An attacker uploads a PHP web shell.",
        "solutions": ["Validate MIME type server-side using file magic bytes", "Rename all uploads to random UUIDs", "Store uploads outside the web root", "Serve user files through a separate domain with no script execution"],
        "reference": "https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload"
    },
    "route-scanning": {
        "name": "Route & Directory Scanning", "icon": "radar",
        "mitre": "T1595", "tactic": "Reconnaissance", "urgency": "Medium",
        "summary": "Automated discovery of hidden endpoints, admin panels, backup files, and API routes.",
        "history": "Scanners like dirbuster and gobuster have made route enumeration a routine first step in web intrusions.",
        "workflow": ["Run a wordlist-based scanner against the target", "Probe found endpoints for authentication weaknesses", "Look for backup or configuration files", "Map API structure for deeper attacks"],
        "signals": ["Sequential 404 responses at high rates", "Requests for common admin/backup paths", "Scanner user-agent strings", "Concentration of requests on one IP"],
        "example": "An attacker runs ffuf against a site and discovers /admin/backup.zip containing database credentials.",
        "solutions": ["Rate-limit and block IPs with excessive 404 responses", "Remove backup and test files from production", "Return identical responses for unknown routes", "Deploy a WAF with scanner signatures"],
        "reference": "https://attack.mitre.org/techniques/T1595/"
    },
    "ssrf": {
        "name": "Server-Side Request Forgery (SSRF)", "icon": "server-cog",
        "mitre": "T1190", "tactic": "Initial Access", "urgency": "Critical",
        "summary": "An attacker makes a trusted server send requests to unintended internal or privileged destinations.",
        "history": "SSRF became especially consequential with cloud metadata services reachable only from trusted workloads.",
        "workflow": ["Find URL-fetching functionality", "Bypass URL validation or redirects", "Reach internal services or cloud metadata", "Steal credentials or invoke privileged APIs", "Pivot using the server's network trust"],
        "signals": ["Requests to loopback, link-local, or private addresses", "Access to cloud metadata endpoints (169.254.169.254)", "Unexpected outbound protocols"],
        "example": "An image importer accepts any URL and can be redirected to the cloud metadata endpoint to retrieve temporary credentials.",
        "solutions": ["Allow-list URL schemes, hosts, and ports", "Revalidate after every redirect", "Deny workload access to sensitive metadata", "Use IMDSv2 or equivalent hardened metadata access"],
        "reference": "https://owasp.org/www-community/attacks/Server_Side_Request_Forgery"
    },
    "api-abuse": {
        "name": "API Abuse & Scraping", "icon": "plug-zap",
        "mitre": "T1530", "tactic": "Collection", "urgency": "Medium",
        "summary": "Excessive or unauthorized API calls to harvest data or exhaust resources.",
        "history": "As services moved to API-first design, data scraping and abuse shifted to API endpoints lacking rate controls.",
        "workflow": ["Enumerate public or leaked API endpoints", "Authenticate or use unauthenticated endpoints", "Request data in bulk using pagination", "Resell or weaponize extracted data"],
        "signals": ["Single client exceeding rate limits repeatedly", "Systematic pagination through all resources", "Unusual access patterns (all users, all records)", "High volume requests outside business hours"],
        "example": "A competitor calls a public pricing API in a loop, extracting a full product catalog every night.",
        "solutions": ["Enforce per-client rate limits", "Require authentication for all data endpoints", "Implement cursor-based pagination with quotas", "Monitor for data-volume anomalies per client"],
        "reference": "https://attack.mitre.org/techniques/T1530/"
    },
    "business-logic": {
        "name": "Business Logic Bypass", "icon": "workflow",
        "mitre": "T1574", "tactic": "Privilege Escalation", "urgency": "High",
        "summary": "An attacker exploits flaws in application workflow to achieve unintended outcomes such as price manipulation or free access.",
        "history": "Business logic attacks are application-specific and rarely detected by signature-based tools because they use legitimate functionality.",
        "workflow": ["Map the application workflow", "Identify assumptions the application makes about state", "Violate assumptions (skip steps, replay requests, modify values)", "Achieve unintended outcome"],
        "signals": ["Workflow steps accessed out of order", "Negative quantity or price values", "Duplicate coupon or voucher redemption", "Actions after apparent cancellation"],
        "example": "An e-commerce site allows quantity -1, resulting in a negative price that creates store credit on checkout.",
        "solutions": ["Enforce business rules server-side at every step", "Validate state transitions", "Log and alert on anomalous transaction values", "Apply negative testing in QA"],
        "reference": "https://owasp.org/www-community/attacks/Business_logic_vulnerability"
    },
    "phishing": {
        "name": "Phishing", "icon": "mail-warning",
        "mitre": "T1566", "tactic": "Initial Access", "urgency": "High",
        "summary": "Deceptive communication induces a user to disclose information or execute attacker content.",
        "history": "Phishing evolved from broad fraudulent email into targeted spearphishing, business-email compromise, and QR lures.",
        "workflow": ["Research a target", "Impersonate a trusted sender or service", "Create urgency", "Capture credentials or deliver a payload", "Use access before it is revoked"],
        "signals": ["Look-alike domains in links", "Reply-to address mismatch", "Unexpected OAuth consent prompts", "New inbox redirect rules", "Login from unusual device after a message"],
        "example": "A fake document-share notice sends an employee to a look-alike login page. The captured session is immediately reused.",
        "solutions": ["Enforce phishing-resistant MFA (FIDO2/passkeys)", "Deploy SPF, DKIM, DMARC on all domains", "Train users to verify requests through a second channel", "Use link sandboxing and URL rewriting"],
        "reference": "https://attack.mitre.org/techniques/T1566/"
    },
    "denial-of-service": {
        "name": "Denial of Service", "icon": "activity",
        "mitre": "T1498", "tactic": "Impact", "urgency": "High",
        "summary": "Traffic or resource exhaustion prevents legitimate users from accessing a service.",
        "history": "DoS evolved from single-source floods to distributed botnets and application-layer exhaustion attacks.",
        "workflow": ["Identify a constrained service or expensive route", "Recruit or rent distributed capacity", "Generate volumetric or application requests", "Sustain pressure to create outage"],
        "signals": ["Abrupt rate or concurrency spike", "Geographic concentration of traffic", "429/503 error rate increase", "CPU or memory saturation without load increase"],
        "example": "Thousands of clients repeatedly request a CPU-intensive search route, exhausting workers while bandwidth remains normal.",
        "solutions": ["Deploy CDN with anycast scrubbing", "Rate-limit by IP and authenticated client", "Cache expensive responses", "Autoscale with cost guards"],
        "reference": "https://attack.mitre.org/techniques/T1498/"
    },
    "supply-chain": {
        "name": "Software Supply Chain Compromise", "icon": "package-x",
        "mitre": "T1195", "tactic": "Initial Access", "urgency": "Critical",
        "summary": "Attackers compromise a dependency, build process, or update channel to reach downstream targets.",
        "history": "Supply-chain blast radius expanded with shared package registries and automated software delivery.",
        "workflow": ["Select a widely trusted package", "Compromise maintainer, build, or signing access", "Insert a targeted payload", "Distribute through legitimate channels"],
        "signals": ["Unexpected dependency or maintainer changes", "Build provenance mismatch", "New outbound behavior after an update", "Install scripts with unexplained execution"],
        "example": "A popular npm package account is taken over and publishes a version containing a credential-stealing install script.",
        "solutions": ["Pin and review dependencies", "Generate and verify SBOMs", "Use isolated reproducible builds with signed provenance", "Monitor egress behavior after software updates"],
        "reference": "https://attack.mitre.org/techniques/T1195/"
    },
    "ransomware": {
        "name": "Ransomware", "icon": "file-lock-2",
        "mitre": "T1486", "tactic": "Impact", "urgency": "Immediate",
        "summary": "Malware encrypts or destroys data after credential theft and lateral movement.",
        "history": "Ransomware progressed from opportunistic device encryption to human-operated intrusions with data theft and extortion.",
        "workflow": ["Gain initial access (phishing or exploit)", "Escalate privilege and disable defenses", "Exfiltrate valuable data", "Destroy recovery paths", "Encrypt systems and demand payment"],
        "signals": ["Mass file renames with new extensions", "Backup deletion or VSS tampering", "Security-tool process termination", "Ransom note file creation"],
        "example": "A compromised remote account is used to reach file servers. Backups are deleted before widespread encryption begins.",
        "solutions": ["Maintain offline immutable backups and test restoration", "Enforce MFA and network segmentation", "Enable EDR with behavioral detection", "Rehearse incident response plans quarterly"],
        "reference": "https://attack.mitre.org/techniques/T1486/"
    },
    "lateral-movement": {
        "name": "Lateral Movement", "icon": "network",
        "mitre": "T1021", "tactic": "Lateral Movement", "urgency": "Critical",
        "summary": "An attacker with initial access moves through a network to reach higher-value targets.",
        "history": "Lateral movement exploits overly permissive internal trust, reused credentials, and unpatched internal services.",
        "workflow": ["Harvest credentials from compromised host", "Identify reachable internal hosts", "Authenticate using stolen credentials or pass-the-hash", "Repeat from new foothold"],
        "signals": ["Logon events from unusual internal sources", "New admin tool usage on servers", "RDP or WMI from workstations", "Credential use across multiple hosts in short time"],
        "example": "After compromising a developer laptop, an attacker uses a cached service account password to access production servers.",
        "solutions": ["Enforce least-privilege and just-in-time access", "Segment networks with zero-trust boundaries", "Detect and alert on credential reuse across hosts", "Deploy privileged access workstations (PAW)"],
        "reference": "https://attack.mitre.org/techniques/T1021/"
    },
    "data-exfiltration": {
        "name": "Data Exfiltration", "icon": "upload-cloud",
        "mitre": "T1041", "tactic": "Exfiltration", "urgency": "Critical",
        "summary": "Sensitive data is transferred out of a network, often over allowed protocols to blend with normal traffic.",
        "history": "Exfiltration techniques range from simple FTP to DNS tunneling, steganography in images, and HTTPS to attacker infrastructure.",
        "workflow": ["Identify and stage target data", "Compress and encrypt the data", "Blend into allowed egress channels (DNS, HTTPS, cloud storage)", "Transfer in small chunks to avoid volume alerts"],
        "signals": ["Unusually large outbound transfers", "Data staging in temp directories", "DNS queries with long subdomains", "Connections to new cloud storage domains", "Access to sensitive data outside normal hours"],
        "example": "An attacker stages customer records in a temp folder, compresses them, and uploads to a personal cloud storage account over HTTPS.",
        "solutions": ["Deploy DLP on egress", "Alert on large outbound transfers to new destinations", "Block unauthorized cloud storage", "Monitor sensitive data access with UEBA"],
        "reference": "https://attack.mitre.org/techniques/T1041/"
    },
    "privilege-escalation": {
        "name": "Privilege Escalation", "icon": "shield-plus",
        "mitre": "T1068", "tactic": "Privilege Escalation", "urgency": "Critical",
        "summary": "An attacker gains higher permissions than initially granted, often by exploiting a vulnerability or misconfiguration.",
        "history": "Privilege escalation is a central post-exploitation step; without elevated rights most persistence and impact techniques fail.",
        "workflow": ["Identify running services, SUID binaries, or sudo misconfigurations", "Exploit a kernel vulnerability or weak permission", "Execute code as root or SYSTEM", "Disable security controls and establish persistence"],
        "signals": ["Unexpected sudo or su usage", "New privileged process spawned by unprivileged parent", "Access to sensitive files that were previously blocked"],
        "example": "A web application running as www-data exploits an outdated kernel module to obtain root and disable auditd.",
        "solutions": ["Apply patches promptly", "Remove unnecessary SUID binaries", "Audit sudo rules regularly", "Use AppArmor or SELinux to confine services"],
        "reference": "https://attack.mitre.org/techniques/T1068/"
    },
    "persistence": {
        "name": "Persistence Mechanisms", "icon": "clock",
        "mitre": "T1505", "tactic": "Persistence", "urgency": "High",
        "summary": "An attacker installs backdoors, scheduled tasks, or web shells to maintain access across reboots and credential rotations.",
        "history": "Persistence ranges from cron jobs and startup scripts to kernel rootkits and firmware implants.",
        "workflow": ["Gain elevated access", "Install a backdoor, web shell, or scheduled task", "Ensure the mechanism survives reboots", "Conceal the artifact from monitoring"],
        "signals": ["New or modified cron jobs", "Unexpected startup scripts", "New web shell files in the web root", "New listening ports opened by unusual processes"],
        "example": "An attacker drops a PHP web shell in an upload directory after exploiting a file-upload vulnerability.",
        "solutions": ["Monitor for new executable files in web-accessible paths", "Alert on cron and startup changes", "Use file-integrity monitoring (FIM)", "Rotate all credentials after any suspected compromise"],
        "reference": "https://attack.mitre.org/techniques/T1505/"
    },
    "cloud-misconfiguration": {
        "name": "Cloud Misconfiguration Exploitation", "icon": "cloud-cog",
        "mitre": "T1530", "tactic": "Collection", "urgency": "Critical",
        "summary": "Publicly exposed storage buckets, databases, or APIs allow unauthorized access to sensitive data.",
        "history": "Mass adoption of cloud services outpaced security education, leading to repeated high-profile exposure incidents.",
        "workflow": ["Scan for exposed cloud resources (S3, Azure Blob, etc.)", "Access without authentication", "Enumerate and download data", "Search for embedded credentials to pivot further"],
        "signals": ["Unusual access to cloud storage from external IPs", "GetObject/ListBucket calls from anonymous principals", "Cloud audit logs showing public access events"],
        "example": "An S3 bucket containing customer invoices is set to public-read during a misconfigured deployment.",
        "solutions": ["Enable public access block on all storage accounts", "Use service control policies (SCPs) to prevent public exposure", "Continuously audit resource policies with CSPM", "Enable CloudTrail/Audit Log alerts on public-access changes"],
        "reference": "https://attack.mitre.org/techniques/T1530/"
    },
    "container-escape": {
        "name": "Container Escape", "icon": "box",
        "mitre": "T1611", "tactic": "Privilege Escalation", "urgency": "Critical",
        "summary": "An attacker breaks out of a container's isolation to access the host operating system.",
        "history": "Container escapes became critical as containerized workloads were granted excessive capabilities or mounted sensitive host paths.",
        "workflow": ["Gain code execution inside a container", "Exploit privileged mode, mounted Docker socket, or kernel vulnerability", "Access the host filesystem", "Compromise other containers or the host"],
        "signals": ["Process spawned by container runtime", "Access to /proc/host or /var/lib/docker", "New privileged container launched", "Kernel exploit attempt patterns"],
        "example": "A container deployed with --privileged and a mounted /var/run/docker.sock allows the attacker to launch new containers with host mounts.",
        "solutions": ["Never use --privileged in production", "Do not mount Docker socket into containers", "Use read-only root filesystems", "Apply seccomp and AppArmor profiles to all containers"],
        "reference": "https://attack.mitre.org/techniques/T1611/"
    },
    "zero-day-exploit": {
        "name": "Zero-Day Exploitation", "icon": "zap",
        "mitre": "T1190", "tactic": "Initial Access", "urgency": "Immediate",
        "summary": "An attacker exploits an unknown or unpatched vulnerability before a fix is available.",
        "history": "Zero-days are bought and sold in underground markets and used by nation-state actors for high-value targets.",
        "workflow": ["Discover or purchase an unknown vulnerability", "Develop a reliable exploit", "Target high-value systems", "Establish access before the vulnerability is discovered"],
        "signals": ["Unexplained crashes or memory corruption", "Unusual process behavior with no known trigger", "Out-of-band network connections from trusted services"],
        "example": "A previously unknown vulnerability in a VPN appliance is used to gain unauthenticated remote code execution.",
        "solutions": ["Apply patches immediately when released", "Use defense-in-depth to limit blast radius", "Deploy behavioral EDR that detects exploitation patterns", "Segment critical systems to limit pivot opportunities"],
        "reference": "https://attack.mitre.org/techniques/T1190/"
    },
    "insider-threat": {
        "name": "Insider Threat", "icon": "user-x",
        "mitre": "T1078", "tactic": "Defense Evasion", "urgency": "High",
        "summary": "A malicious or negligent employee misuses legitimate access to harm the organization.",
        "history": "Insider incidents account for a significant fraction of data breaches and are harder to detect than external attacks.",
        "workflow": ["Use legitimate credentials and access", "Access data or systems outside normal job scope", "Exfiltrate, sabotage, or sell information", "Cover tracks using authorized tools"],
        "signals": ["Access to data outside normal job role", "Large downloads outside business hours", "Access after resignation or during notice period", "Disabling logging or audit tools"],
        "example": "A departing employee downloads the entire customer database to personal cloud storage the week before leaving.",
        "solutions": ["Implement UEBA to detect anomalous access patterns", "Revoke access immediately on resignation", "Apply data classification and DLP", "Conduct regular access reviews"],
        "reference": "https://attack.mitre.org/techniques/T1078/"
    },
    "cryptomining": {
        "name": "Cryptojacking", "icon": "cpu",
        "mitre": "T1496", "tactic": "Impact", "urgency": "Medium",
        "summary": "Attacker deploys cryptocurrency miners on compromised systems to generate revenue using victim resources.",
        "history": "Cryptojacking surged with cryptocurrency prices and became a common outcome of server compromises.",
        "workflow": ["Gain code execution via web exploit, misconfiguration, or credential theft", "Download and install a mining binary", "Connect to a mining pool over allowed protocols", "Maximize CPU/GPU usage while avoiding detection"],
        "signals": ["Sustained high CPU utilization with no corresponding user load", "Connections to known mining pool domains or IPs", "New executable files in temp directories", "Process name masquerading as system process"],
        "example": "After exploiting a vulnerable CMS plugin, an attacker installs XMRig on the server and mines Monero through HTTPS.",
        "solutions": ["Monitor CPU utilization baselines and alert on sustained anomalies", "Block known mining pool domains and IPs", "Apply egress filtering on outbound connections", "Use immutable infrastructure to prevent binary installation"],
        "reference": "https://attack.mitre.org/techniques/T1496/"
    },
    "log-tampering": {
        "name": "Log Tampering & Anti-Forensics", "icon": "file-x",
        "mitre": "T1070", "tactic": "Defense Evasion", "urgency": "High",
        "summary": "An attacker modifies, deletes, or truncates log files to hide their activity from investigators.",
        "history": "Log tampering is a standard post-compromise step; without logs, incident response is severely hampered.",
        "workflow": ["Identify log storage locations", "Disable or stop logging services", "Delete or truncate relevant log files", "Cover specific entries if full deletion is risky"],
        "signals": ["Audit log gaps (timestamp discontinuity)", "Log rotation at unusual times", "Log daemon process termination", "Changed log file permissions"],
        "example": "After a breach, an attacker deletes /var/log/auth.log and stops syslog to remove evidence of their lateral movement.",
        "solutions": ["Stream logs to an external SIEM in real time", "Use append-only log storage", "Alert on auditd process termination or log truncation", "Apply file-integrity monitoring to log directories"],
        "reference": "https://attack.mitre.org/techniques/T1070/"
    },
}