ATTACKS = {
    "credential-attacks": {
        "name": "Brute Force & Credential Stuffing", "icon": "key-round", "mitre": "T1110", "tactic": "Credential Access", "urgency": "Critical after successful access",
        "summary": "Automated password guessing or reuse of credentials stolen from another service.",
        "history": "Password guessing is one of the oldest intrusion methods. Large breach collections and inexpensive automation evolved it into credential stuffing against many accounts at once.",
        "workflow": ["Acquire usernames or leaked credential pairs", "Distribute attempts across IPs and devices", "Tune request rate to avoid lockouts", "Reuse a successful session for discovery or privilege escalation"],
        "signals": ["Bursts of 401/403 responses", "One source targeting many accounts", "One account receiving attempts from many regions", "A successful login after repeated failures", "New device, token, or privilege activity"],
        "example": "An attacker tries a reused email/password against a shopping account. A login succeeds after 37 failures, followed by an address and recovery-email change.",
        "solutions": {"Individual": "Use unique passwords, a password manager, phishing-resistant MFA, and review active sessions.", "Application": "Rate-limit by account and source, use breached-password screening, generic errors, and risk-based challenges.", "Enterprise": "Correlate identity telemetry, revoke suspicious sessions, enforce conditional access, and investigate post-login behavior."},
        "reference": "https://attack.mitre.org/techniques/T1110/"
    },
    "sql-injection": {
        "name": "SQL Injection", "icon": "database-zap", "mitre": "T1190", "tactic": "Initial Access", "urgency": "Immediate",
        "summary": "Untrusted input changes the structure or meaning of an application database query.",
        "history": "SQL injection became prominent as dynamic database-backed websites spread. It remains dangerous wherever applications concatenate input into queries.",
        "workflow": ["Find a database-backed parameter", "Probe quoting and error behavior", "Infer database structure", "Extract, modify, or delete data", "Attempt operating-system execution where database privileges allow it"],
        "signals": ["UNION SELECT, comment markers, or time-delay functions", "Database syntax errors", "Unusual response sizes or latency", "Enumeration of schema tables", "Abnormal database-account activity"],
        "example": "A vulnerable product lookup concatenates an ID. Input containing a boolean condition causes the query to return every product instead of one.",
        "solutions": {"Code": "Use parameterized queries and safe ORM bindings; never build SQL with string concatenation.", "Database": "Apply least privilege, separate read/write identities, encrypt sensitive fields, and enable audit logs.", "Edge & testing": "Add WAF defense-in-depth, SAST/DAST tests, dependency review, and regression cases for every input path."},
        "reference": "https://owasp.org/www-community/attacks/SQL_Injection"
    },
    "command-injection": {
        "name": "Command Injection", "icon": "terminal-square", "mitre": "T1059", "tactic": "Execution", "urgency": "Immediate",
        "summary": "Attacker-controlled input reaches an operating-system command interpreter.", "history": "Command injection has persisted from early CGI programs through modern API wrappers and automation services that invoke shell tools.",
        "workflow": ["Locate input passed to a system utility", "Test shell separators or substitutions", "Execute discovery commands", "Download tooling or establish persistence", "Access secrets and move laterally"],
        "signals": ["Shell metacharacters in parameters", "Unexpected child processes", "Web service spawning a shell", "Outbound connections after a request", "New executable or scheduled task"],
        "example": "A diagnostic endpoint runs a ping command using an unsanitized hostname. A separator appended to the hostname launches a second command.",
        "solutions": {"Preferred": "Remove shell execution and use a native library API.", "When unavoidable": "Use fixed commands, strict allow-lists, argument arrays, low-privilege service accounts, and sandboxing.", "Incident": "Isolate the host, preserve process/network evidence, rotate secrets, and rebuild when integrity cannot be proven."}, "reference": "https://attack.mitre.org/techniques/T1059/"
    },
    "cross-site-scripting": {
        "name": "Cross-Site Scripting", "icon": "code-xml", "mitre": "T1189", "tactic": "Initial Access", "urgency": "High",
        "summary": "Untrusted content executes as script in another user’s browser.", "history": "XSS emerged with scriptable web applications and now appears as reflected, stored, and DOM-based variants.",
        "workflow": ["Find reflected or stored input", "Determine HTML, attribute, URL, or script context", "Create a context-specific payload", "Deliver it to a victim", "Steal data or perform actions in the victim session"],
        "signals": ["Script tags or event handlers in input", "Unexpected DOM mutation", "Content-Security-Policy reports", "Session use from a new device", "Stored markup in user content"],
        "example": "A comment field stores unencoded HTML. Anyone viewing the page executes the attacker’s script in the site origin.",
        "solutions": {"Output": "Apply contextual encoding and use frameworks that escape by default.", "Input": "Sanitize only when rich HTML is required; validate URLs and dangerous attributes.", "Browser": "Deploy strict CSP, HttpOnly/SameSite cookies, Trusted Types where appropriate, and invalidate exposed sessions."}, "reference": "https://owasp.org/www-community/attacks/xss/"
    },
    "path-traversal": {"name":"Path Traversal","icon":"folder-search","mitre":"T1083","tactic":"Discovery","urgency":"High","summary":"Manipulated paths escape an intended directory and access unauthorized files.","history":"Traversal flaws have affected file servers, archives, download handlers, and template systems across operating systems.","workflow":["Find a filename or path parameter","Submit encoded parent-directory sequences","Probe known configuration files","Read secrets or source code","Use exposed credentials for further access"],"signals":["../ or encoded equivalents","Requests for password or configuration files","Abnormal download sizes","Repeated path normalization failures"],"example":"A download endpoint joins user input to an upload folder without checking the final canonical path.","solutions":{"Code":"Resolve the canonical path and verify it remains beneath an allow-listed root.","Design":"Map opaque identifiers to server-side files instead of accepting paths.","Operations":"Run with minimal filesystem permissions and rotate any exposed secrets."},"reference":"https://owasp.org/www-community/attacks/Path_Traversal"},
    "phishing": {"name":"Phishing","icon":"mail-warning","mitre":"T1566","tactic":"Initial Access","urgency":"High","summary":"Deceptive communication induces a user to disclose information or execute attacker content.","history":"Phishing evolved from broad fraudulent email into targeted spearphishing, business-email compromise, QR lures, and consent attacks.","workflow":["Research a target","Impersonate a trusted sender or service","Create urgency","Capture credentials or deliver a file/link","Use access before it is revoked"],"signals":["Look-alike domains","Reply-to mismatch","Unexpected OAuth consent","New inbox rules","Login from an unusual device after a message"],"example":"A fake document-share notice sends an employee to a look-alike login page and immediately reuses the captured session.","solutions":{"Individual":"Verify requests through a second channel and use phishing-resistant MFA.","Email":"Enforce SPF, DKIM, DMARC, attachment sandboxing, and URL analysis.","Identity":"Use conditional access, token protection, rapid session revocation, and consent governance."},"reference":"https://attack.mitre.org/techniques/T1566/"},
    "ransomware": {"name":"Ransomware","icon":"file-lock-2","mitre":"T1486","tactic":"Impact","urgency":"Immediate","summary":"Malware encrypts or destroys data, commonly after credential theft and lateral movement.","history":"Ransomware progressed from opportunistic device encryption to human-operated intrusions with data theft and extortion.","workflow":["Gain initial access","Escalate privilege and disable defenses","Discover and exfiltrate valuable data","Destroy recovery paths","Encrypt systems and demand payment"],"signals":["Mass file renames","Backup deletion","Security-tool tampering","Rapid SMB writes","Known encryption or ransom-note behavior"],"example":"A compromised remote account is used to reach file servers; backup snapshots are deleted before widespread encryption begins.","solutions":{"Prevent":"Patch edge systems, enforce MFA, segment networks, restrict admin tools, and maintain EDR.","Recover":"Keep offline immutable backups and rehearse restoration.","Respond":"Isolate affected segments, preserve evidence, invoke crisis plans, and coordinate legal and regulatory obligations."},"reference":"https://attack.mitre.org/techniques/T1486/"},
    "denial-of-service": {"name":"Denial of Service","icon":"activity","mitre":"T1498","tactic":"Impact","urgency":"High to Immediate","summary":"Traffic or resource exhaustion prevents legitimate users from accessing a service.","history":"DoS evolved from single-source floods to distributed botnets, reflection/amplification, and application-layer exhaustion.","workflow":["Identify a constrained service or expensive route","Recruit or rent distributed capacity","Generate volumetric or application requests","Adapt around filters","Sustain pressure to create outage"],"signals":["Abrupt rate or concurrency increase","Geographic or autonomous-system concentration","429/503 spikes","Resource saturation","Expensive endpoint concentration"],"example":"Thousands of clients repeatedly request a CPU-intensive search route, exhausting workers while bandwidth remains normal.","solutions":{"Edge":"Use CDN, anycast scrubbing, rate limits, challenges, and source reputation.","Application":"Cache responses, cap work, queue expensive jobs, and reserve authenticated capacity.","Operations":"Autoscale with cost guards, define provider escalation, and rehearse status communication."},"reference":"https://attack.mitre.org/techniques/T1498/"},
    "ssrf": {"name":"Server-Side Request Forgery","icon":"server-cog","mitre":"T1190","tactic":"Initial Access","urgency":"Critical","summary":"An attacker makes a trusted server send requests to unintended internal or privileged destinations.","history":"SSRF became especially consequential with cloud metadata services and internal APIs reachable only from trusted workloads.","workflow":["Find URL-fetching functionality","Bypass URL validation or redirects","Reach internal services or metadata","Steal credentials or invoke privileged APIs","Pivot using the server’s network trust"],"signals":["Requests to loopback, link-local, or private addresses","DNS rebinding patterns","Unexpected outbound protocols","Metadata-service access","Outbound calls inconsistent with user workflow"],"example":"An image importer accepts any URL and can be redirected to a cloud metadata endpoint that returns temporary credentials.","solutions":{"Validation":"Allow-list schemes, hosts, ports, and resolved addresses; revalidate every redirect.","Network":"Deny workload access to sensitive metadata and segment egress.","Cloud":"Use hardened metadata modes, short-lived least-privilege identities, and credential-use alerts."},"reference":"https://owasp.org/www-community/attacks/Server_Side_Request_Forgery"},
    "supply-chain": {"name":"Software Supply Chain Compromise","icon":"package-x","mitre":"T1195","tactic":"Initial Access","urgency":"Critical","summary":"Attackers compromise a dependency, build process, update channel, or supplier to reach downstream targets.","history":"Supply-chain attacks predate modern package managers but their blast radius expanded with shared dependencies and automated software delivery.","workflow":["Select a widely trusted supplier or package","Compromise source, maintainer, build, or signing access","Insert a targeted payload","Distribute through legitimate channels","Activate only on selected victims"],"signals":["Unexpected dependency or maintainer changes","Build provenance mismatch","New outbound behavior after an update","Signature or hash anomalies","Install scripts with unexplained execution"],"example":"A popular dependency account is taken over and publishes a version containing a credential-stealing install script.","solutions":{"Development":"Pin and review dependencies, minimize install scripts, generate SBOMs, and scan secrets.","Delivery":"Use isolated reproducible builds, signed provenance, protected release identities, and staged rollout.","Runtime":"Apply egress controls and monitor new behavior after software changes."},"reference":"https://attack.mitre.org/techniques/T1195/"}
}
