ALTER TABLE risk_events ADD COLUMN IF NOT EXISTS source VARCHAR(30) NOT NULL DEFAULT 'rule';
ALTER TABLE risk_events ADD COLUMN IF NOT EXISTS source_status VARCHAR(30) NOT NULL DEFAULT 'uploaded';
ALTER TABLE risk_events ADD COLUMN IF NOT EXISTS attack_type VARCHAR(100);
ALTER TABLE risk_events ADD COLUMN IF NOT EXISTS analyst_label VARCHAR(30);
ALTER TABLE risk_events ADD COLUMN IF NOT EXISTS reviewed_by BIGINT REFERENCES users(id);
ALTER TABLE risk_events ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS model_retraining_runs (
    id BIGSERIAL PRIMARY KEY, model_version VARCHAR(100) NOT NULL, label_count INTEGER NOT NULL,
    f1_score DOUBLE PRECISION NOT NULL, metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
