(() => {
"use strict";
class ForensicSystem3D{
constructor(el){this.el=el;this.parts=[[-3,1.2,0,1.2,.8,.6,.15,.39,.92],[-1,1.2,0,.4,.8,.6,.05,.55,.72],[1,1.2,0,.4,.8,.6,.85,.48,.12],[3,1.2,0,1.2,.8,.6,.49,.35,.85],[-2,-1,0,1,.8,.6,.12,.58,.42],[0,-1,0,1,.8,.6,.1,.45,.8],[2,-1,0,1,.8,.6,.8,.22,.32]];this.rx=-.2;this.ry=.35;this.drag=false;this.last=[0,0];this.scroll=0;this.start()}
start(){const c=document.createElement("canvas");c.className="forensic-3d-canvas";this.el.replaceChildren(c);this.c=c;const g=c.getContext("webgl",{antialias:true,alpha:true});if(!g)return;this.g=g;
const v='attribute vec3 a;uniform mat4 m;uniform vec3 c;varying vec3 v;void main(){v=c;gl_Position=m*vec4(a,1.0);}';
const f='precision mediump float;varying vec3 v;void main(){gl_FragColor=vec4(v,1.0);}';
const sh=(t,s)=>{const x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);return x};const p=g.createProgram();g.attachShader(p,sh(g.VERTEX_SHADER,v));g.attachShader(p,sh(g.FRAGMENT_SHADER,f));g.linkProgram(p);g.useProgram(p);
const b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(this.cube()),g.STATIC_DRAW);const a=g.getAttribLocation(p,"a");g.enableVertexAttribArray(a);g.vertexAttribPointer(a,3,g.FLOAT,false,0,0);this.m=g.getUniformLocation(p,"m");this.col=g.getUniformLocation(p,"c");
addEventListener("resize",()=>this.resize(),{passive:true});c.onpointerdown=e=>{this.drag=true;this.last=[e.clientX,e.clientY];c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!this.drag)return;this.ry+=(e.clientX-this.last[0])*.008;this.rx+=(e.clientY-this.last[1])*.006;this.last=[e.clientX,e.clientY]};c.onpointerup=()=>this.drag=false;c.onpointercancel=()=>this.drag=false;addEventListener("scroll",()=>{const d=Math.max(1,document.body.scrollHeight-innerHeight);this.scroll=Math.min(1,Math.max(0,scrollY/d))},{passive:true});this.resize();this.draw()}
cube(){const q=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]],f=[[0,1,2,0,2,3],[4,6,5,4,7,6],[0,4,5,0,5,1],[2,6,7,2,7,3],[0,3,7,0,7,4],[1,5,6,1,6,2]],o=[];f.forEach(x=>x.forEach(i=>o.push(...q[i])));return o}
resize(){this.d=Math.min(devicePixelRatio||1,1.7);this.c.width=(this.el.clientWidth||800)*this.d;this.c.height=(this.el.clientHeight||520)*this.d;this.g.viewport(0,0,this.c.width,this.c.height)}
mat(){const a=Math.PI/4,asp=this.c.width/this.c.height,t=1/Math.tan(a/2),nf=1/(.1-100),P=[t/asp,0,0,0,0,t,0,0,0,0,(100+.1)*nf,-1,0,0,2*100*.1*nf,0],cx=Math.cos(this.rx),sx=Math.sin(this.rx),cy=Math.cos(this.ry),sy=Math.sin(this.ry),R=[cy*cx,sy*sx,-sy*cx,0,0,cx,sx,0,sy*cx,-cy*sx,cy*cx,0,0,0,0,1],T=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,-12,1];return this.mul(P,this.mul(R,T))}
mul(a,b){const o=new Array(16);for(let r=0;r<4;r++)for(let c=0;c<4;c++)o[c+r*4]=a[r*4]*b[c]+a[r*4+1]*b[c+4]+a[r*4+2]*b[c+8]+a[r*4+3]*b[c+12];return o}
draw(){const g=this.g;g.clearColor(.97,.98,1,0);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.enable(g.DEPTH_TEST);const P=this.mat(),e=Math.sin(this.scroll*Math.PI)*1.8,t=performance.now()/1500;this.parts.forEach((p,i)=>{const x=p[0]+Math.sign(p[0]||1)*e*(i%2?1.2:.8),y=p[1]+Math.sign(p[1]||1)*e*(i%3?1:.7),z=Math.sin(t+i)*.05,s=[p[3],p[4],p[5]],M=[s[0],0,0,0,0,s[1],0,0,0,0,s[2],0,x,y,z,1];g.uniformMatrix4fv(this.m,false,new Float32Array(this.mul(P,M)));g.uniform3fv(this.col,new Float32Array(p.slice(6,9)));g.drawArrays(g.TRIANGLES,0,36)});requestAnimationFrame(()=>this.draw())}}
document.addEventListener("DOMContentLoaded",()=>{const e=document.getElementById("hero-server-canvas");if(e)new ForensicSystem3D(e)});
})();